const actions = {
  SET_USER: "SET_USER",
  CREATE_USER: "CREATE_USER",
  GET_ALL_DREAMS_CURRENT_USER: "GET_ALL_DREAMS_CURRENT_USER",
  GET_ALL_DREAMS_CURRENT_USER_CAT: "GET_ALL_DREAMS_CURRENT_USER_CAT",
  RESET_LIST: "RESET_LIST",
  RESET_LIST_CAT: "RESET_LIST_CAT"
};
export default actions;
